### ISSUE TITLE
Tileserver stops after 3 days

### ISSUE THREAD

**Issue by CarlosVMX1** [123FLO321/SwiftTileserverCache#4]
Hello, I'm using SwiftTileserverCache for a Discord channel but after 3 days the messages stops getting maps, I have rebooted Docker and that fixed it, so my question is if I need to reboot Docker every other day or if I have some configuration missing to flush the cache or something like that.

**Comment by 123FLO321** [comment]
Please check if there are errors in the logs. You should not need to restart SwiftTileserverCache.

**Comment by lokixx** [comment]
Not sure if related, but i'm seeing increased memory usage overtime with latest SwiftTileserverCache. Docker down up fixes it, but is it possible there is a memory leak?

**Comment by 123FLO321** [comment]
whats using the memory? SwiftTileserverCache?

**Comment by lokixx** [comment]
yes SwiftTilerserverCacheApp

**Comment by CarlosVMX1** [comment]
SwiftTilerserverCacheApp is using 6%-10% of my server memory (8gb), so for now I put a cron to restart docker each 12 hours to keep all working

**Comment by 123FLO321** [comment]
1.0.4+ potentially fixes this.
If this is still an issue please re-open this.

**Comment by 123FLO321** [comment]
Still an issue but fixed in #6 

Cause of issue: https://bugs.swift.org/browse/SR-6450
Fixed by updating Swift to 5.2.3

**Comment by CarlosVMX1** [comment]
Thank you, I changed to the vapor branch and will report how it goes, for now all looks good.
